### ISSUE TITLE
External SD card not mounted in TWRP (64Gb)

### ISSUE THREAD

**Issue by jonsat2** [grogg/android_device_lge_pplus#2]
With the last version (May 01, 2016) I can't mount my external SD card in TWRP.
Card is a Samsung 64Gb, reformatted into V10 H901, it is correctly recognized into MM rom and in previous MM TWRP.

**Comment by grogg** [comment]
This report is not confirmed.  A new build with exfat enabled has been posted.  Please test and report back.

**Comment by grogg** [comment]
Bug confirmed as resolved after enabling exfat.
